server:
  port: 5001

spring:
  application:
    name:  microservicecloud-config-server     #配置中心服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nocol0609/microservicecloud-config.git
          default-label: main
#          uri: git@github.com:nocol0609/microservicecloud-config.git #GitHub上面的git仓库名字
#          strict-host-key-checking: false
#          ignore-local-ssh-settings: true
#          private-key: |
#                        -----BEGIN OPENSSH PRIVATE KEY-----
                         # ......
#                        -----END OPENSSH PRIVATE KEY-----

